### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by saipriya-ar** [HzFu/DENet_GlaucomaScreen#3]
sir,
 we are pursuing b.tech information technology  in anna university .can you provide us the dataset for glaucoma (origa and sces dataset) for our final year project .It would be very helpful to us . can you mail us through arsaipriyakrishna2011@gmail.com

Thanks in advance

**Comment by HzFu** [comment]
Thank you for interest in our work.
Unfortunately, the ORIGA and SCES data cannot be released due to the clinical policy.
 
But, we organized a glaucoma challenge on MICCAI 2018, including disc/cup segmentation, glaucoma screening, and localization of Fovea. The registration is open. If you are interested, you can register it from:
https://refuge.grand-challenge.org/home/

**Comment by saipriya-ar** [comment]
the sindi dataset too

**Comment by saipriya-ar** [comment]
what is the MICCAI 2018 CHALLENGE ,would it help us in our final year project
